export const ADD_SEARCH_RESULTS = 'ADD_SEARCH_RESULTS';
export const ADD_RANDOM_RESTAURANT = 'ADD_RANDOM_RESTAURANT';
export const ADD_USER_SELECTION = 'ADD_USER_SELECTION';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT';
export const ADD_LIKES = 'ADD_LIKES';
